spring.application.name=SecurityApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/ProductionReady?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=Redx@0711
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#Security Configs
#in memory User Details
#spring.security.user.name=user
#spring.security.user.password=pass

#logging config
logging.level.com.sharmashivansh2907.SecurityAPp.SecurityApplication.serviceImpl=INFO


jwt.secretKey = kjdhs34h2h1k23hjkhkj3h1kh43k1kjhkjhk45hk4hkhkj3h41khkjh4khk465h4khk342kh4243jhkj3h45khk

deploy.env = development